export interface CobeturaCommand{
    id: number,
    proyecto: string,
    tipo_de_celda: number,
    cell_name: string,
    banda: string,
    frb: string,
    cellcov_af: string,
    cellcov_be: string,
    cellcov_nu: string,
    cellcov_pre: string,
    isd: number,
    cobertura: string,
    etilt: number,
    maxtilt: number,
    mintilt: number,
    change_tilt: number,
    rs: number,
    limit: number,
    change_rs: number,
    step: number,
    delta_cellcov: string,
    delta_trafficusermax: number,
    delta_ulinterference: number,
    created_at: Date
}